apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: talend-registry
  containers:
    - name: talend-builder
      image: artifactory.datapwn.com/tlnd-docker-prod/talend/common/tsbi/custom-builder:3.1.10-20230315171124
      tty: true
      command:
        - cat
      resources:
        requests:
          memory: "2G"
          cpu: "2"
        limits:
          memory: "8G"
          cpu: "6"
      volumeMounts:
        - name: efs-jenkins-components-maven
          mountPath: /root/.m2/repository
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
    - name: docker-daemon
      image: artifactory.datapwn.com/docker-io-remote/docker:23.0.6-dind
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: true
  volumes:
    - name: efs-jenkins-components-maven
      persistentVolumeClaim:
        claimName: efs-jenkins-components-m2
